server:
  port: 8081

basis:
  simple:
    rpc:
      simple-rpc-server-port: 8888
      max-wait-time: 15
      nacos:
        group-name: consumer-group
        cluster-name: consumer-cluster


spring:
  application:
    name: simple-rpc-consumer

nacos:
  discovery:
    server-addr: wenpan-host:8848
